### ISSUE TITLE
Unable to use with second Google account

### ISSUE THREAD

**Issue by mjpvandenberg** [ericyd/gdrive-copy#1]
When first accessing the application it says 

> The application "Copy Folder" needs authorization to run.

In the popup, in the top-right corner I select my second Google account, then click Allow. Unfortunately, the application keeps saying 

> The application "Copy Folder" needs authorization to run.

If I select my first Google account, the error message disappears and I can start using the application. However, my first Google account is a personal one. I need to use the application with my work account.

Is there a workaround?

**Comment by ericyd** [comment]
I would like to add an account switcher to the app, but for now the best solution is to open the app in an incognito window with the desired Google account.  This prevents any conflicts from multiple accounts.

**Comment by AzureBlaze** [comment]
In case anyone reads this one work around is it get the account number ([image](https://i.imgur.com/XCmUsJj.png)) of the account you want to use, which you can see in any gmail/google windows and then add ?authuser={n} to the end of the url where n is the account number.

**Comment by ericyd** [comment]
Since this app relies entirely on Google's built in authentication system, I'm going to consider this a bug that is outside the control of this application.  There are undoubtedly ways to make the access to this application more robust, but at the current time my resources are limited and this particular behavior is not consistently reproducible in any of my testing.
