### ISSUE TITLE
Summary of failures for Google Apps Script: Copy Folder

### ISSUE THREAD

**Issue by christinadeville** [ericyd/gdrive-copy#19]
This will not stop, I need this to stop copying the folder and sending to my sales rep. in his google drive

### Specify your

* operating system:
* browser:

**Comment by ericyd** [comment]
Have you tried the stop button? You might need to reload the page to enable it


---- On Mon, 17 Apr 2017 19:20:21 -0700 notifications@github.com wrote ----

This will not stop, I need this to stop copying the folder and sending to my sales rep. in his google drive

Are you requesting a feature or reporting a bug?

What is the current behavior?

What is the expected behavior?

How would you reproduce the current behavior (if this is a bug)?

Specify your

operating system:
browser:

**Comment by ericyd** [comment]
It should also stop if you delete the file in the folder that says "do not delete" 

---- On Mon, 17 Apr 2017 19:20:21 -0700 notifications@github.com wrote ----

This will not stop, I need this to stop copying the folder and sending to my sales rep. in his google drive

Are you requesting a feature or reporting a bug?

What is the current behavior?

What is the expected behavior?

How would you reproduce the current behavior (if this is a bug)?

Specify your

operating system:
browser:

**Comment by christinadeville** [comment]
the instructions on the website said to click pause and it will pause all
copies from duplicating but I am still receiving notification emails, which
i forwarded to you

*A huge solar spill, it's just called a NICE DAY! *

Christina DeVille
VP of Business Development
C: 760.501.8747
W: 800.385.1075
cdeville@freedomsolarco.com
www.freedomsolarco.com

**Comment by christinadeville** [comment]
ok I deleted it but now my sales rep. has the copy folder forms duplicated
multiple times?
I deleted the copy folder on my side that had the multiple files duplicated.

Will that delete on his side as well?

What went wrong because I am trying to use this website for this reason but
if it's buggy that would create an issue for me?

*A huge solar spill, it's just called a NICE DAY! *

Christina DeVille
VP of Business Development
C: 760.501.8747
W: 800.385.1075
cdeville@freedomsolarco.com
www.freedomsolarco.com

**Comment by christinadeville** [comment]
it is still doing it and sending the same email?


*A huge solar spill, it's just called a NICE DAY! *

Christina DeVille
VP of Business Development
C: 760.501.8747
W: 800.385.1075
cdeville@freedomsolarco.com
www.freedomsolarco.com

**Comment by ericyd** [comment]
Try removing permissions for the app

https://webapps.stackexchange.com/questions/30841/how-do-i-remove-permission-from-an-app-that-i-gave-google-oauth-access-to


---- On Mon, 17 Apr 2017 19:56:07 -0700 notifications@github.com wrote ----

it is still doing it and sending the same email?


*A huge solar spill, it's just called a NICE DAY! *

Christina DeVille
VP of Business Development
C: 760.501.8747
W: 800.385.1075
cdeville@freedomsolarco.com
www.freedomsolarco.com

**Comment by christinadeville** [comment]
I did that and I am still receiving the email error message

*A huge solar spill, it's just called a NICE DAY! *

Christina DeVille
VP of Business Development
C: 760.501.8747
W: 800.385.1075
cdeville@freedomsolarco.com
www.freedomsolarco.com

**Comment by ericyd** [comment]
I've removed a chunk of code that I believe was responsible for first introducing the infinite loop bug.
