### ISSUE TITLE
How do I get this off my machine??

### ISSUE THREAD

**Issue by 4endymion** [ericyd/gdrive-copy#9]
I added this as a Chrome extension on to my Vivaldi browser, and now, for the life of me, I can't figure out how to remove. It doesn't have options to delete like all my other extensions.

That's the major issue, but the issue that's driven me to want to do this is that the extension is causing all of my Google platforms to display in funky manners since installing. It's a drag.

**Comment by 4endymion** [comment]
Nevermind. Found how to nuke it. Would've been nice if it didn't hijack my entire Gdrive experience. Thanks for trying.

**Comment by ericyd** [comment]
I'm happy you got this resolved, but could you be more specific about "hijacking your entire Gdrive experience"? I haven't added anything to this app that should affect anything in the way your Google Drive displays or functions.

**Comment by 4endymion** [comment]
Icons and menus were disappearing from all my Google apps. Once I removed the app, the browser completely froze-up as well, and had to reboot the machine because it' wouldn't force quit. I'm using Vivaldi, which runs on the same framework as Chrome, but just might not play well with certain apps, esp when they're not interpreted as straight extensions within the browser. Thanks for the reply.

**Comment by ericyd** [comment]
For anyone else experiencing the same issue, you do not have to add the app to your browser in order to use it.  You can access the app by clicking the "Visit Website" button in the Chrome Webstore listing, which will take you directly to the [app page](https://script.google.com/macros/s/AKfycbxbGNGajrxv-HbX2sVY2OTu7yj9VvxlOMOeQblZFuq7rYm7uyo/exec).
